version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true

    ports:
      - "8000:8000"
      
      #Volumes make a relation between the container and our project
      #so things we create in one are created on the other
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

